from pathlib import Path

import streamlit as st

st.set_page_config(
    page_title="UK Innovation Ecosystem Monitor",
    page_icon="📊",
    layout="wide",
)

st.title("UK Innovation Ecosystem Monitor")

st.markdown(
    """
    This Streamlit app brings together the three datasets highlighted in the mini hackathon:

    1. **OECD MSTI / GBARD** – national intent and portfolio mix for public R&D budgets.
    2. **Ofcom Connected Nations + IMD** – regional digital infrastructure readiness paired with deprivation.
    3. **GtR+ (coming soon)** – project-level collaboration data to explore networks and missed opportunities.

    Use the navigation menu on the left to jump between the analysis pages. Each page cites the
    processed CSV/Parquet file it relies on so you can trace results back to the reproducible pipeline.
    """
)

st.divider()

st.subheader("How to run locally")
st.code("streamlit run Home.py", language="bash")
st.markdown(
    """
    The app expects the processed data files generated by:

    - `python src/data_download.py msti --countries ...`
    - `python src/build_lad_metrics.py`
    - forthcoming GtR+ aggregation scripts (network page currently a stub).
    """
)
